[package]
name = "aoc_client"
version = "0.1.0"
authors = ["Juan de Bravo <juandebravo@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }